digits:
  digit_3: 3
  digit_5: 5
  digit_8: 8
  digit_255: 255
regexs:
  email: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
  password:   \A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}\z
  telephone: \A[0-9]{10}\z
hotel:
  phone: 024-6666-8888
  email: hotelier@gmail.com
auto_check_booking_delay: 30
time_to_review_minutes: 5
image_size:
  s_240x240: [240, 240]
